### ISSUE TITLE
tests missing data

### ISSUE THREAD

**Issue by ehomer** [aoterodelaroza/gibbs2#4]
Many of the tests require input files from a path that does not exist. Perhaps I am wrong to expect that these would be available, but I expected that I could just run each of the tests. They will not run. For example, file `tests/002_fits/001_fits.ing` has the following text `phase BM3 file ../dat/c_pbe/c.res` but there is no `dat` directory. Is this a misunderstanding on my part or an oversight in what should be included?

**Comment by aoterodelaroza** [comment]
Oooops, sorry about that and thanks for pointing it out. I've just
uploaded the dat/ directory. Please, pull and try again. I still need
to fine-tune the tests, so ignore fails for now.

**Comment by ehomer** [comment]
Thanks! That worked!
