### ISSUE TITLE
how to build the tests with cmake

### ISSUE THREAD

**Issue by WeiLiPenguin** [aoterodelaroza/gibbs2#5]
Hi,
 
I was trying to build the package with cmake,  I set in CMakeList:
```cmake
option(BUILD_TESTING "Enable the regression tests for the gibbs2 build." ON)
```
and get error:
```bash
list does not recognize sub-command TRANSFORM
```
Maybe I am doing the wrong way,
Please help me.
Thanks a lot!
BR!

Wei

**Comment by aoterodelaroza** [comment]
Hi Wei: you need a cmake version of at least 3.12 to run the tests. I
just pushed a change to make sure cmake checks the version in the
tests directory. If you don't have access to a recent cmake, then I
recommend you simply deactivate the tests.

**Comment by WeiLiPenguin** [comment]
Hi, 
Thanks for the reply.  the tests could be build now with "new" version of cmake.
sorry for more questions below.
Best Regards!
Wei

I use intel-oneapi-2021.1.2
but some tests fail:
some of the "error" like below, should I accept it? or try lower the opt flags or something else?

8:CHECK:001_simple/ref/001_io.eos        
11:CHECK:002_fits/ref/001_fits.outg
13:CHECK:002_fits/ref/001_fits_dH.aux
15:CHECK:002_fits/ref/001_fits.efit
16:CHECK:002_fits/ref/001_fits_efit.aux
18:CHECK:002_fits/ref/001_fits.eos
19:CHECK:002_fits/ref/001_fits.eos_static
21:CHECK:003_tmodels/ref/001_tmodels.outg
28:CHECK:003_tmodels/ref/001_tmodels.eos
38:CHECK:004_eec/ref/001_eec.outg
48:CHECK:005_elec/ref/001_elec.outg
57:CHECK:006_phases/ref/001_phases.outg
60:CHECK:006_phases/ref/001_phases.dgtp
66:CHECK:006_phases/ref/001_phases.eos
70:CHECK:006_phases/ref/001_phases.tpstab

some of the "error" like below, should I accept it? or try lower the opt flags or something else?
                                                                                
      Start 66: CHECK:006_phases/ref/001_phases.eos                             
14/15 Test #66: CHECK:006_phases/ref/001_phases.eos ......***Failed    0.31 sec 
----------------                                                                
##9       #:6   <== -5.4469271511E-03                                           
##9       #:6   ==> -5.4469270399E-03                                           
@ Absolute error = 1.1120000000e-10, Relative error = 2.0415180741e-8           
----------------                                                                
##10      #:6   <== 3.6516181590E-03                                            
##10      #:6   ==> 3.6516182725E-03                                            
@ Absolute error = 1.1350000000e-10, Relative error = 3.1082110740e-8           
----------------
##13      #:6   <== 3.2851709177E-02
##13      #:6   ==> 3.2851709291E-02
@ Absolute error = 1.1400000000e-10, Relative error = 3.4701390843e-9
----------------
##15      #:6   <== 2.4808775170E-02
##15      #:6   ==> 2.4808775285E-02
@ Absolute error = 1.1500000000e-10, Relative error = 4.6354565758e-9
----------------
##17      #:6   <== -3.1595787193E-02
##17      #:6   ==> -3.1595787077E-02
@ Absolute error = 1.1600000000e-10, Relative error = 3.6713755450e-9
----------------
##21      #:6   <== 2.6051461161E-02
##21      #:6   ==> 2.6051461315E-02
@ Absolute error = 1.5400000000e-10, Relative error = 5.9113766805e-9
----------------
##23      #:6   <== 7.6951750768E-03
##23      #:6   ==> 7.6951751936E-03
@ Absolute error = 1.1680000000e-10, Relative error = 1.5178342121e-8
----------------
##24      #:6   <== -1.8350418309E-02
##24      #:6   ==> -1.8350418192E-02
@ Absolute error = 1.1700000000e-10, Relative error = 6.3758764937e-9
----------------
##25      #:6   <== -1.1294288642E-02
##25      #:6   ==> -1.1294288525E-02
@ Absolute error = 1.1700000000e-10, Relative error = 1.0359218267e-8
----------------
##26      #:6   <== -1.9035956621E-02
##26      #:6   ==> -1.9035956503E-02
@ Absolute error = 1.1800000000e-10, Relative error = 6.1987954207e-9
----------------
.....

**Comment by aoterodelaroza** [comment]
Those error magnitudes are probably fine.

**Comment by WeiLiPenguin** [comment]
Thanks!
