### ISSUE TITLE
Is the data in the example correct?

### ISSUE THREAD

**Issue by likenihood** [aoterodelaroza/gibbs2#6]
I think the energy of MgO  should only be 0.43128(Ha/ Unit cell) instead of 73.5 in the data.

In addition, the Gibbs free energy of MgO calculated from the example is too large. 
I think there is some error here, If I remember correctly1 hartree is equal to 27.2114 eV

**Comment by aoterodelaroza** [comment]
Hi @likenihood . The energies for the MgO example in gibbs2 come from a pseudopotential/plane-waves calculation whose details have been lost in the mists of time. In this method, the energy zero is arbitrary, and shifting the E(V) curve up and down does not have an effect on any of the calculated properties.
